### ISSUE TITLE
Problem with MNIST download data in example

### ISSUE THREAD

**Issue by gigasquid** [thinktopic/cortex#184]
Cloned the Cortex project fresh and tried to run the MNIST example. Ran into a problem downloading the data.

```
Loading mnist training dataset.
Exception in thread "main" java.util.zip.ZipException: Not in GZIP format, compiling:(mnist_classification/core.clj:83:1)
```
It looks like it was trying to download this file from S3
`https://s3-us-west-2.amazonaws.com/thinktopic.datasets/mnist/train-images-idx3-ubyte.gz `

### Full Reproduction steps
```
✔ ~/workspace/clojureland 
10:14 $ git clone git@github.com:thinktopic/cortex.git
Cloning into 'cortex'...
remote: Counting objects: 9177, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 9177 (delta 7), reused 17 (delta 3), pack-reused 9126
Receiving objects: 100% (9177/9177), 4.97 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (5022/5022), done.
Checking connectivity... done.
✔ ~/workspace/clojureland 
10:14 $ cd cortex/
✔ ~/workspace/clojureland/cortex [master|✔] 
10:14 $ lein install
Compiling 1 source files to /Users/cmeier/workspace/clojureland/cortex/target/classes
Created /Users/cmeier/workspace/clojureland/cortex/target/cortex-0.9.10-SNAPSHOT.jar
Wrote /Users/cmeier/workspace/clojureland/cortex/pom.xml
Installed jar and pom into local repo.
✔ ~/workspace/clojureland/cortex [master|✔] 
10:15 $ cd experiment/
✔ ~/workspace/clojureland/cortex/experiment [master|✔] 
10:15 $ lein install
Compiling Garden...
Compiling "resources/public/css/app.css"...
Wrote: resources/public/css/app.css
Successful
Compiling ClojureScript...
Compiling "resources/public/js/app.js" from ["src/cljs/"]...
Successfully compiled "resources/public/js/app.js" in 21.392 seconds.
Created /Users/cmeier/workspace/clojureland/cortex/experiment/target/experiment-0.9.10-SNAPSHOT.jar
Wrote /Users/cmeier/workspace/clojureland/cortex/experiment/pom.xml
Installed jar and pom into local repo.
✔ ~/workspace/clojureland/cortex/experiment [master|✔] 
10:16 $ cd ../examples/mnist-classification/
✔ ~/workspace/clojureland/cortex/examples/mnist-classification [master|✔] 
10:16 $ lein run
Compiling mnist-classification.main
Welcome! Please wait while we compile some Clojure code...
Reflection warning, cognitect/transit.clj:142:19 - call to static method writer on com.cognitect.transit.TransitFactory can't be resolved (argument types: unknown, java.io.OutputStream, unknown).
Loading mnist training dataset.
Exception in thread "main" java.util.zip.ZipException: Not in GZIP format, compiling:(mnist_classification/core.clj:83:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at mnist_classification.main$_main.invokeStatic(main.clj:22)
	at mnist_classification.main$_main.doInvoke(main.clj:18)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init2075935919469398506.clj:1)
	at user$eval5.invoke(form-init2075935919469398506.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at cortex.datasets.util$dataset_input_stream.invokeStatic(util.clj:43)
	at cortex.datasets.util$dataset_input_stream.doInvoke(util.clj:29)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at cortex.datasets.mnist$mnist_data_stream.invokeStatic(mnist.clj:53)
	at cortex.datasets.mnist$mnist_data_stream.invoke(mnist.clj:49)
	at cortex.datasets.mnist$load_data.invokeStatic(mnist.clj:59)
	at cortex.datasets.mnist$load_data.invoke(mnist.clj:57)
	at cortex.datasets.mnist$training_dataset.invokeStatic(mnist.clj:98)
	at cortex.datasets.mnist$training_dataset.invoke(mnist.clj:97)
	at mnist_classification.core$timed_get_dataset.invokeStatic(core.clj:78)
	at mnist_classification.core$timed_get_dataset.invoke(core.clj:74)
	at mnist_classification.core$eval63166.invokeStatic(core.clj:84)
	at mnist_classification.core$eval63166.invoke(core.clj:83)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 45 more
```

**Comment by gigasquid** [comment]
Solved my problem: I had an old version of the data files in `~/.cortex`. I deleted them and reran and everything is cool. Closing the issue.

**Comment by harold** [comment]
@gigasquid --- Glad you worked this out. This is a little speedbump for super-early adopters (not that many people had data in the old format in their `~/.cortex` :D

Always good to hear from you, sorry again for the trouble. Take care!
